/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Point {
  x: number
  y: number
}
export interface Rect {
  left: number
  top: number
  right: number
  bottom: number
}
export interface Color {
  r: number
  g: number
  b: number
}
export const MAGENTA: Color
export function readImageData(path: string): Promise<ImageData>
export function writeImageData(path: string, imageData: ImageData): Promise<void>
export function imageSearch(source: ImageData, target: ImageData, variant?: number | undefined | null, transColor?: Color | undefined | null): Promise<Point | null>
export function multipleImageSearch(source: ImageData, target: ImageData, variant?: number | undefined | null, transColor?: Color | undefined | null): Promise<Array<Point>>
export const enum Key {
  None = 0,
  LButton = 1,
  RButton = 2,
  Cancel = 3,
  MButton = 4,
  XButton1 = 5,
  XButton2 = 6,
  Back = 8,
  Tab = 9,
  LineFeed = 10,
  Clear = 12,
  Enter = 13,
  ShiftKey = 16,
  ControlKey = 17,
  Menu = 18,
  Pause = 19,
  CapsLock = 20,
  FinalMode = 24,
  Escape = 27,
  Space = 32,
  PageUp = 33,
  PageDown = 34,
  End = 35,
  Home = 36,
  Left = 37,
  Up = 38,
  Right = 39,
  Down = 40,
  Select = 41,
  Print = 42,
  Execute = 43,
  PrintScreen = 44,
  Insert = 45,
  Delete = 46,
  Help = 47,
  D0 = 48,
  D1 = 49,
  D2 = 50,
  D3 = 51,
  D4 = 52,
  D5 = 53,
  D6 = 54,
  D7 = 55,
  D8 = 56,
  D9 = 57,
  A = 65,
  B = 66,
  C = 67,
  D = 68,
  E = 69,
  F = 70,
  G = 71,
  H = 72,
  I = 73,
  J = 74,
  K = 75,
  L = 76,
  M = 77,
  N = 78,
  O = 79,
  P = 80,
  Q = 81,
  R = 82,
  S = 83,
  T = 84,
  U = 85,
  V = 86,
  W = 87,
  X = 88,
  Y = 89,
  Z = 90,
  LWin = 91,
  RWin = 92,
  Apps = 93,
  Sleep = 95,
  NumPad0 = 96,
  NumPad1 = 97,
  NumPad2 = 98,
  NumPad3 = 99,
  NumPad4 = 100,
  NumPad5 = 101,
  NumPad6 = 102,
  NumPad7 = 103,
  NumPad8 = 104,
  NumPad9 = 105,
  Multiply = 106,
  Add = 107,
  Separator = 108,
  Subtract = 109,
  Decimal = 110,
  Divide = 111,
  F1 = 112,
  F2 = 113,
  F3 = 114,
  F4 = 115,
  F5 = 116,
  F6 = 117,
  F7 = 118,
  F8 = 119,
  F9 = 120,
  F10 = 121,
  F11 = 122,
  F12 = 123,
  F13 = 124,
  F14 = 125,
  F15 = 126,
  F16 = 127,
  F17 = 128,
  F18 = 129,
  F19 = 130,
  F20 = 131,
  F21 = 132,
  F22 = 133,
  F23 = 134,
  F24 = 135,
  NumLock = 144,
  Scroll = 145,
  LShiftKey = 160,
  RShiftKey = 161,
  LControlKey = 162,
  RControlKey = 163,
  LMenu = 164,
  RMenu = 165,
  BrowserBack = 166,
  BrowserForward = 167,
  BrowserRefresh = 168,
  BrowserStop = 169,
  BrowserSearch = 170,
  BrowserFavorites = 171,
  BrowserHome = 172,
  VolumeMute = 173,
  VolumeDown = 174,
  VolumeUp = 175,
  MediaNextTrack = 176,
  MediaPreviousTrack = 177,
  MediaStop = 178,
  MediaPlayPause = 179,
  LaunchMail = 180,
  SelectMedia = 181,
  LaunchApplication1 = 182,
  LaunchApplication2 = 183,
  ProcessKey = 229,
  Packet = 231,
  Attn = 246,
  Exsel = 248,
  EraseEof = 249,
  Play = 250,
  Zoom = 251,
  NoName = 252,
  Pa1 = 253
}
export const enum MouseButton {
  Left = 0,
  Right = 1,
  Middle = 2
}
export function mouseMove(x: number, y: number): Promise<boolean>
export function mousePress(button: MouseButton): Promise<boolean>
export function mouseRelease(button: MouseButton): Promise<boolean>
export function mouseClick(button: MouseButton, x: number, y: number): Promise<boolean>
export function keyClick(key: Key): Promise<boolean>
export function keyPress(key: Key): Promise<boolean>
export function keyRelease(key: Key): Promise<boolean>
export function getMousePosition(): Promise<Point>
export function typeText(text: string): Promise<void>
export function getScreenSize(): Promise<Point>
export function takeScreenshot(x: number, y: number, width: number, height: number): Promise<ImageData>
export function getForegroundWindow(): Promise<Window | null>
export function findWindowByTitle(title: string): Promise<Window | null>
export class ImageData {
  data: Array<number>
  width: number
  height: number
  pixelWidth: number
}
export class Window {
  setMinimize(): Promise<void>
  setMaximize(): Promise<void>
  getTitle(): Promise<string>
  getWindowRect(): Promise<Rect>
  setPosition(x: number, y: number): Promise<void>
  setSize(width: number, height: number): Promise<void>
  setForeground(): Promise<boolean>
}
